---
- name: Ensure apt pkgs are installed.
  apt:
    name: "{{ item.name }}"
  sudo: yes
  with_items:
    - name: dos2unix
    - name: gawk
    - name: sed
    - name: htop
    - name: jq
    - name: p7zip
    - name: source-highlight
    - name: silversearcher-ag
    - name: tig
    - name: tmux
    - name: tree
  tags:
    - productivity

- name: Ensure pip2 pkgs are installed.
  pip:
    name: "{{ item.name }}"
    executable: pip2
  sudo: yes
  with_items:
    - name: percol
  tags:
    - productivity
