---
- name: Ensure apt pkgs are installed.
  apt:
    name: "{{ item.name }}"
  sudo: yes
  with_items:
    - name: imagemagick
    - name: libopencv-dev
  tags:
    - image_processing

- include: ../../python3/tasks/pip.yml
  vars:
    pkgs:
      - name: matplotlib
        state: present
  tags:
    - image_processing
