---
- name: Ensure python3 is installed.
  apt:
    name: "{{ item.name }}"
  sudo: yes
  with_items:
    - name: python3
    - name: python3-pip
  tags:
    - python
    - python3

- include: ../../python3/tasks/pip.yml
  vars:
    pkgs:
      - name: pip
        state: latest
      # - name: pipenv
      #   state: present
  tags:
    - python
    - python3
